language: scala
scala:
  - 2.10.0
jdk:
  - openjdk7
  - oraclejdk7
install: /bin/true # always succeeds
script:
  - mvn -B test-compile
  - mvn -B -Dbenchmark.executorServiceType=fixed-thread-pool test -Ptravis
  - mvn -B -Dbenchmark.executorServiceType=scala-forkjoin-pool test -Ptravis
  - mvn -B -Dbenchmark.executorServiceType=java-forkjoin-pool test -Ptravis
  - mvn -B -Dbenchmark.executorServiceType=thread-pool test -Ptravis

